### ISSUE TITLE
As a facilitator, I want to know how to share my rooms calendar so that I can submit it

### ISSUE THREAD

**Issue by Zandrr** [BeTandem/scheduler_frontend#18]
This can be slightly tweaked for rooms/mentors/members, but it's largely the same

**Comment by thejinxters** [comment]
This is the best solution I can come up with for the moment:

https://docs.google.com/document/d/1iCm63pH6nGQ-GSAc5C7vDBpqITlhDmuOk3bmtfzv1cE/edit
