### ISSUE TITLE
As a facilitator, I want to click links on the sidebar that will take me to each of the pages to submit my schdule, so that I can easily navigate back and forth between sections

### ISSUE THREAD

**Issue by thejinxters** [BeTandem/scheduler_frontend#27]
Should have the following nav:
- Getting Started
- Room Availability
- Mentor Availability
- Mentee Availability
- Submit All Availabilities

**Comment by sthoma** [comment]
@thejinxters Do these pages need cards as well or should the nav links just go to blank stubs?

**Comment by thejinxters** [comment]
The pages should be represented in the other tasks, so just do blank stubs for right now.

**Comment by sthoma** [comment]
:thumbsup:
