### ISSUE TITLE
As a facilitator, I want the login modal to be static, so that I can't be stuck logged out

### ISSUE THREAD

**Issue by sthoma** [BeTandem/scheduler_frontend#40]
Login modal can be dismissed without logging in by clicking anywhere outside of the modal

**Comment by thejinxters** [comment]
Not on my computer. What browser are you using?

**Comment by sthoma** [comment]
Chrome 48

**Comment by thejinxters** [comment]
Same, and it is a static modal, cant click anywhere to get rid of it. Are you sure you have the latest version of the master branch?

**Comment by sthoma** [comment]
Yeah everything's up to date

**Comment by sthoma** [comment]
Ok weird. Just restarted Chrome and it's working right now

**Comment by thejinxters** [comment]
Chrome has been buggy lately, its been a pain for development. Good to hear things are working properly, guess we can close this issue.
