### ISSUE TITLE
As a user I want to understand what I am signing up for  with Tandem so that I know how my google data will be used and what implications signing up has.

### ISSUE THREAD

**Issue by sthoma** [BeTandem/scheduler_frontend#42]
send user info to backend for storage in db

**Comment by sthoma** [comment]
@thejinxters didn't adding frontend google auth capabilities accomplish this card?

**Comment by thejinxters** [comment]
@sthoma yes. but it looks terrible cause I just created a plain button for google log-in. I think this story should be about building out the login page, so a user understands what they are signing up for, etc. I've updated the story
