### ISSUE TITLE
As a user, I don't understand "There are some 60 minute blocks of time that work for everyone to meet. Choose one and Tandem will do the rest" and want it changed, so that I can understand

### ISSUE THREAD

**Issue by thejinxters** [BeTandem/scheduler_frontend#97]

**Comment by sthoma** [comment]
"There are several 60 minute blocks of time when everyone can meet. Choose a day and general time of day, and Tandem will do the rest."

A bit better?

**Comment by thejinxters** [comment]
I think we should completely change it.. and actually explain what they are doing, like this:

"Choose time-block below and we will automatically find the best meeting time within that block that works for everyone."
